var searchData=
[
  ['clearuicomponents_0',['ClearUIComponents',['../class_maui_app1_1_1_views_1_1_rota_page.html#aa4a7e3f2c3455fb3034d0a27e7672cd5',1,'MauiApp1::Views::RotaPage']]],
  ['color_1',['color',['../classandroidx_1_1appcompat_1_1_r_1_1color.html',1,'androidx.appcompat.R.color'],['../classandroidx_1_1browser_1_1_r_1_1color.html',1,'androidx.browser.R.color'],['../classandroidx_1_1cardview_1_1_r_1_1color.html',1,'androidx.cardview.R.color'],['../classandroidx_1_1constraintlayout_1_1widget_1_1_r_1_1color.html',1,'androidx.constraintlayout.widget.R.color'],['../classandroidx_1_1core_1_1_r_1_1color.html',1,'androidx.core.R.color'],['../classandroidx_1_1drawerlayout_1_1_r_1_1color.html',1,'androidx.drawerlayout.R.color'],['../classandroidx_1_1media_1_1_r_1_1color.html',1,'androidx.media.R.color'],['../classandroidx_1_1recyclerview_1_1_r_1_1color.html',1,'androidx.recyclerview.R.color'],['../classandroidx_1_1swiperefreshlayout_1_1_r_1_1color.html',1,'androidx.swiperefreshlayout.R.color'],['../classandroidx_1_1transition_1_1_r_1_1color.html',1,'androidx.transition.R.color'],['../classandroidx_1_1viewpager2_1_1_r_1_1color.html',1,'androidx.viewpager2.R.color'],['../classcom_1_1bumptech_1_1glide_1_1_r_1_1color.html',1,'com.bumptech.glide.R.color'],['../classcom_1_1google_1_1android_1_1material_1_1_r_1_1color.html',1,'com.google.android.material.R.color'],['../classcom_1_1microsoft_1_1maui_1_1_r_1_1color.html',1,'com.microsoft.maui.R.color'],['../class_maui_app1_1_1_resource_1_1_color.html',1,'MauiApp1.Resource.Color']]],
  ['continent_2',['Continent',['../class_maui_app1_1_1_models_1_1_continent.html',1,'MauiApp1::Models']]],
  ['continentpage_3',['ContinentPage',['../class_maui_app1_1_1_views_1_1_continent_page.html',1,'MauiApp1::Views']]],
  ['continentservice_4',['ContinentService',['../class_maui_app1_1_1_services_1_1_continent_service.html',1,'MauiApp1::Services']]],
  ['createrotafrominput_5',['CreateRotaFromInput',['../class_maui_app1_1_1_views_1_1_rota_page.html#a928c51b104318bda61f531daa8905db0',1,'MauiApp1::Views::RotaPage']]]
];
