var searchData=
[
  ['ialerttypeservice_0',['IAlertTypeService',['../interface_maui_app1_1_1_services_1_1_i_alert_type_service.html',1,'MauiApp1::Services']]],
  ['ibuildingtypeservice_1',['IBuildingTypeService',['../interface_maui_app1_1_1_services_1_1_i_building_type_service.html',1,'MauiApp1::Services']]],
  ['icontinentservice_2',['IContinentService',['../interface_maui_app1_1_1_services_1_1_i_continent_service.html',1,'MauiApp1::Services']]],
  ['id_3',['id',['../classandroidx_1_1activity_1_1_r_1_1id.html',1,'androidx.activity.R.id'],['../classandroidx_1_1appcompat_1_1_r_1_1id.html',1,'androidx.appcompat.R.id'],['../classandroidx_1_1browser_1_1_r_1_1id.html',1,'androidx.browser.R.id'],['../classandroidx_1_1constraintlayout_1_1widget_1_1_r_1_1id.html',1,'androidx.constraintlayout.widget.R.id'],['../classandroidx_1_1coordinatorlayout_1_1_r_1_1id.html',1,'androidx.coordinatorlayout.R.id'],['../classandroidx_1_1core_1_1_r_1_1id.html',1,'androidx.core.R.id'],['../classandroidx_1_1drawerlayout_1_1_r_1_1id.html',1,'androidx.drawerlayout.R.id'],['../classandroidx_1_1fragment_1_1_r_1_1id.html',1,'androidx.fragment.R.id'],['../classandroidx_1_1lifecycle_1_1runtime_1_1_r_1_1id.html',1,'androidx.lifecycle.runtime.R.id'],['../classandroidx_1_1lifecycle_1_1viewmodel_1_1_r_1_1id.html',1,'androidx.lifecycle.viewmodel.R.id'],['../classandroidx_1_1media_1_1_r_1_1id.html',1,'androidx.media.R.id'],['../classandroidx_1_1navigation_1_1fragment_1_1_r_1_1id.html',1,'androidx.navigation.fragment.R.id'],['../classandroidx_1_1navigation_1_1_r_1_1id.html',1,'androidx.navigation.R.id'],['../classandroidx_1_1recyclerview_1_1_r_1_1id.html',1,'androidx.recyclerview.R.id'],['../classandroidx_1_1savedstate_1_1_r_1_1id.html',1,'androidx.savedstate.R.id'],['../classandroidx_1_1swiperefreshlayout_1_1_r_1_1id.html',1,'androidx.swiperefreshlayout.R.id'],['../classandroidx_1_1transition_1_1_r_1_1id.html',1,'androidx.transition.R.id'],['../classandroidx_1_1viewpager2_1_1_r_1_1id.html',1,'androidx.viewpager2.R.id'],['../classandroidx_1_1window_1_1_r_1_1id.html',1,'androidx.window.R.id'],['../classcom_1_1bumptech_1_1glide_1_1_r_1_1id.html',1,'com.bumptech.glide.R.id'],['../classcom_1_1google_1_1android_1_1material_1_1_r_1_1id.html',1,'com.google.android.material.R.id'],['../classcom_1_1microsoft_1_1maui_1_1_r_1_1id.html',1,'com.microsoft.maui.R.id'],['../class_maui_app1_1_1_resource_1_1_id.html',1,'MauiApp1.Resource.Id']]],
  ['integer_4',['integer',['../classandroidx_1_1appcompat_1_1_r_1_1integer.html',1,'androidx.appcompat.R.integer'],['../classandroidx_1_1constraintlayout_1_1widget_1_1_r_1_1integer.html',1,'androidx.constraintlayout.widget.R.integer'],['../classandroidx_1_1core_1_1_r_1_1integer.html',1,'androidx.core.R.integer'],['../classandroidx_1_1drawerlayout_1_1_r_1_1integer.html',1,'androidx.drawerlayout.R.integer'],['../classandroidx_1_1media_1_1_r_1_1integer.html',1,'androidx.media.R.integer'],['../classandroidx_1_1navigation_1_1ui_1_1_r_1_1integer.html',1,'androidx.navigation.ui.R.integer'],['../classandroidx_1_1recyclerview_1_1_r_1_1integer.html',1,'androidx.recyclerview.R.integer'],['../classandroidx_1_1swiperefreshlayout_1_1_r_1_1integer.html',1,'androidx.swiperefreshlayout.R.integer'],['../classandroidx_1_1transition_1_1_r_1_1integer.html',1,'androidx.transition.R.integer'],['../classandroidx_1_1viewpager2_1_1_r_1_1integer.html',1,'androidx.viewpager2.R.integer'],['../classcom_1_1bumptech_1_1glide_1_1_r_1_1integer.html',1,'com.bumptech.glide.R.integer'],['../classcom_1_1google_1_1android_1_1material_1_1_r_1_1integer.html',1,'com.google.android.material.R.integer'],['../classcom_1_1microsoft_1_1maui_1_1_r_1_1integer.html',1,'com.microsoft.maui.R.integer'],['../class_maui_app1_1_1_resource_1_1_integer.html',1,'MauiApp1.Resource.Integer']]],
  ['interpolator_5',['interpolator',['../classandroidx_1_1appcompat_1_1_r_1_1interpolator.html',1,'androidx.appcompat.R.interpolator'],['../classandroidx_1_1constraintlayout_1_1widget_1_1_r_1_1interpolator.html',1,'androidx.constraintlayout.widget.R.interpolator'],['../classcom_1_1google_1_1android_1_1material_1_1_r_1_1interpolator.html',1,'com.google.android.material.R.interpolator'],['../classcom_1_1microsoft_1_1maui_1_1_r_1_1interpolator.html',1,'com.microsoft.maui.R.interpolator'],['../class_maui_app1_1_1_resource_1_1_interpolator.html',1,'MauiApp1.Resource.Interpolator']]],
  ['iorganisationservice_6',['IOrganisationService',['../interface_maui_app1_1_1_services_1_1_i_organisation_service.html',1,'MauiApp1::Services']]],
  ['iroleservice_7',['IRoleService',['../interface_maui_app1_1_1_services_1_1_i_role_service.html',1,'MauiApp1::Services']]],
  ['irotaservice_8',['IRotaService',['../interface_maui_app1_1_1_services_1_1_i_rota_service.html',1,'MauiApp1::Services']]],
  ['iskillservice_9',['ISkillService',['../interface_maui_app1_1_1_services_1_1_i_skill_service.html',1,'MauiApp1::Services']]],
  ['isystemtypeservice_10',['ISystemTypeService',['../interface_maui_app1_1_1_services_1_1_i_system_type_service.html',1,'MauiApp1::Services']]]
];
